spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/telemicro}
    username: ${DB_USERNAME:telemicro}
    password: ${DB_PASSWORD:telemicro_local_only}
app:
  security:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
